name: dotnet.test.e2e
description: Allows to run e2e a built dotnet project and upload the result to TestSpace

inputs:
  target_browser:
    description: Target browser (chromium, firefox and webkit)
    required: true
  url:
    description: URL of the application to be tested
    required: true
  working_directory:
    description: Working directory
    required: true

runs:
  using: composite
  steps:
    - name: Restore Dependencies
      run: npm ci
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Install ${{ inputs.target_browser }}
      run: npx playwright install ${{ inputs.target_browser }}
      working-directory: ${{ inputs.working_directory }}
      shell: bash

    - name: Test
      env:
        TEST_RUN_TARGET_BROWSER: ${{ inputs.target_browser }}
        TEST_RUN_URL: ${{ inputs.url }}
      run: npm run test -- --format junit > result.xml
      shell: bash
      continue-on-error: true
      working-directory: ${{ inputs.working_directory }}

    - name: Install TestSpace CLI
      uses: testspace-com/setup-testspace@v1
      with:
        domain: mihben

    - name: Publish Test Result
      run: testspace result.xml
      shell: bash
      working-directory: ${{ inputs.working_directory }}
