# yaml-language-server: $schema=
name: dotnet.release
description: Allows to create releases

runs:
  using: composite
  steps:
    - name: Release
      uses: googleapis/release-please-action@v4
      with:
        target-branch: develop
        release-type: simple
