name: dotnet.restore-dependencies
description: Restore NuGet dependencies and cache them

inputs:
  working-directory:
    description: Directory where the solution can be found
    default: src

runs:
  using: composite
  steps:
    - name: Restore Dependecies
      run: dotnet restore
      shell: bash
      working-directory: ${{ inputs.working-directory }}
