events { }

http { 
    include mime.types;
    types {
        application/wasm wasm;
    }

    server {
        listen 80;
        index index.html;

        gzip on;
        gzip_types image/* application/javascript;
        gzip_min_length 1000;

        location / {
            root /var/www/web;
            try_files $uri $uri /index.html =404;
        }
    }   
 }